### ISSUE TITLE
Rare random crash in ClassInheritanceMultiMap when creating Cubes constructor

### ISSUE THREAD

**Issue by Barteks2x** [Barteks2x/CubicChunks#102]
Similar issue to the one fixed here: https://github.com/Barteks2x/CubicChunks/commit/bcb80931955171e06810c7873de5973d4dcec8ea

```
[20:16:32] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_101]
	at net.minecraft.util.Util.runTask(Util.java:26) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1108) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:406) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_101]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_101]
	at net.minecraft.util.ClassInheritanceMultiMap.<init>(ClassInheritanceMultiMap.java:27) ~[ClassInheritanceMultiMap.class:?]
	at cubicchunks.world.EntityContainer.<init>(EntityContainer.java:52) ~[EntityContainer.class:?]
	at cubicchunks.world.cube.Cube.<init>(Cube.java:107) ~[Cube.class:?]
	at cubicchunks.client.CubeProviderClient.loadCube(CubeProviderClient.java:102) ~[CubeProviderClient.class:?]
	at cubicchunks.network.ClientHandler.handle(ClientHandler.java:87) ~[ClientHandler.class:?]
	at cubicchunks.network.ClientHandler.lambda$handle$0(ClientHandler.java:69) ~[ClientHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
	at net.minecraft.util.Util.runTask(Util.java:25) ~[Util.class:?]
	... 15 more
```

Minecraft completely ignores the exception.

**Comment by Niko-sk2x** [comment]
This is actually vanilla concurrency issue, I just don't know why it works in vanilla. It seems like it's just a coincidence that it works.

**Comment by Niko-sk2x** [comment]
Apparently it got reported to forge and closed without fixing it: https://github.com/MinecraftForge/MinecraftForge/issues/3081

**Comment by kashike** [comment]
http://hopper.minecraft.net/crashes/minecraft/MCX-2687334/
http://hopper.minecraft.net/crashes/minecraft/MCX-2976674/
http://pastebin.com/raw/TJcNq0UT
http://pastebin.ca/raw/3381075

**Comment by Niko-sk2x** [comment]
If I figure out how to automate starting and stopping minecraft I will try to reproduce it in vanilla on 1.11
