### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by ghost** [Barteks2x/CubicChunks#173]
```
$: ./gradlew --stacktrace build
This mapping 'snapshot_20170209' was designed for MC 1.11! Use at your own peril.
Found AccessTransformer: cubicchunks_at.cfg
Git describe information: "v0.0-523-g3a2cfe0" in unknown/incorrect format

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':runtime'.
> Could not find deobf.net.malisis:malisiscore:1.11.2-5.0.2-SNAPSHOT.
  Searched in the following locations:
      http://files.minecraftforge.net/maven/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/maven-metadata.xml
      http://files.minecraftforge.net/maven/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.pom
      http://files.minecraftforge.net/maven/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.jar
      https://repo1.maven.org/maven2/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.pom
      https://repo1.maven.org/maven2/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.jar
      https://libraries.minecraft.net/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/maven-metadata.xml
      https://libraries.minecraft.net/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.pom
      https://libraries.minecraft.net/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.jar
      file:/home/babs/.m2/repository/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/maven-metadata.xml
      file:/home/babs/.m2/repository/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.pom
      file:/home/babs/.m2/repository/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.jar
      https://jcenter.bintray.com/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/maven-metadata.xml
      https://jcenter.bintray.com/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.pom
      https://jcenter.bintray.com/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.jar
      https://oss.sonatype.org/content/repositories/public/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/maven-metadata.xml
      https://oss.sonatype.org/content/repositories/public/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.pom
      https://oss.sonatype.org/content/repositories/public/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.jar
      http://repo.spongepowered.org/maven/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/maven-metadata.xml
      http://repo.spongepowered.org/maven/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.pom
      http://repo.spongepowered.org/maven/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.jar
      file:/home/babs/.gradle/caches/minecraft/deobfedDeps/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/maven-metadata.xml
      file:/home/babs/.gradle/caches/minecraft/deobfedDeps/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.pom
      file:/home/babs/.gradle/caches/minecraft/deobfedDeps/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.jar
      file:/home/babs/Stuff/CubicChunks/.gradle/minecraft/malisiscore-1.11.2-5.0.2-SNAPSHOT.jar
      file:/home/babs/Stuff/CubicChunks/.gradle/minecraft/malisiscore.jar
  Required by:
      project :

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':runtime'.
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.rethrowFailure(DefaultLenientConfiguration.java:179)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultResolvedConfiguration.rethrowFailure(DefaultResolvedConfiguration.java:48)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultResolvedConfiguration.getFirstLevelModuleDependencies(DefaultResolvedConfiguration.java:66)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolvedConfiguration.getFirstLevelModuleDependencies(ErrorHandlingConfigurationResolver.java:281)
	at com.github.jengelman.gradle.plugins.shadow.internal.DefaultDependencyFilter.resolve(DefaultDependencyFilter.groovy:28)
	at com.github.jengelman.gradle.plugins.shadow.internal.DefaultDependencyFilter$_resolve_closure2.doCall(DefaultDependencyFilter.groovy:36)
	at com.github.jengelman.gradle.plugins.shadow.internal.DefaultDependencyFilter.resolve(DefaultDependencyFilter.groovy:35)
	at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar.getIncludedDependencies(ShadowJar.java:76)
	at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar_Decorated.getIncludedDependencies(Unknown Source)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.TaskPropertyInfo$4.create(TaskPropertyInfo.java:99)
	at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:217)
	at org.gradle.api.internal.project.taskfactory.TaskPropertyInfo.getValue(TaskPropertyInfo.java:97)
	at org.gradle.api.internal.project.taskfactory.TaskClassValidator$FutureValue.call(TaskClassValidator.java:62)
	at org.gradle.util.GUtil.uncheckedCall(GUtil.java:402)
	at org.gradle.api.internal.file.collections.BuildDependenciesOnlyFileCollectionResolveContext.add(BuildDependenciesOnlyFileCollectionResolveContext.java:72)
	at org.gradle.api.internal.file.collections.BuildDependenciesOnlyFileCollectionResolveContext.add(BuildDependenciesOnlyFileCollectionResolveContext.java:84)
	at org.gradle.api.internal.tasks.TaskPropertyFileCollection.visitContents(TaskPropertyFileCollection.java:53)
	at org.gradle.api.internal.file.CompositeFileCollection.visitDependencies(CompositeFileCollection.java:166)
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:88)
	at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmpyEdges.getNodeValues(CachingDirectedGraphWalker.java:202)
	at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:112)
	at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:64)
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.doResolve(CachingTaskDependencyResolveContext.java:76)
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.resolve(CachingTaskDependencyResolveContext.java:65)
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:55)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.addToTaskGraph(DefaultTaskExecutionPlan.java:139)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.addTasks(DefaultTaskGraphExecuter.java:101)
	at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:47)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
	at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:44)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
	at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:47)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(DefaultBuildConfigurationActionExecuter.java:36)
	at org.gradle.initialization.DefaultGradleLauncher$CalculateTaskGraphAction.execute(DefaultGradleLauncher.java:228)
	at org.gradle.initialization.DefaultGradleLauncher$CalculateTaskGraphAction.execute(DefaultGradleLauncher.java:225)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:166)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:113)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:96)
	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find deobf.net.malisis:malisiscore:1.11.2-5.0.2-SNAPSHOT.
Searched in the following locations:
    http://files.minecraftforge.net/maven/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/maven-metadata.xml
    http://files.minecraftforge.net/maven/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.pom
    http://files.minecraftforge.net/maven/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.jar
    https://repo1.maven.org/maven2/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/maven-metadata.xml
    https://repo1.maven.org/maven2/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.pom
    https://repo1.maven.org/maven2/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.jar
    https://libraries.minecraft.net/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/maven-metadata.xml
    https://libraries.minecraft.net/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.pom
    https://libraries.minecraft.net/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.jar
    file:/home/babs/.m2/repository/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/maven-metadata.xml
    file:/home/babs/.m2/repository/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.pom
    file:/home/babs/.m2/repository/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.jar
    https://jcenter.bintray.com/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/maven-metadata.xml
    https://jcenter.bintray.com/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.pom
    https://jcenter.bintray.com/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.jar
    https://oss.sonatype.org/content/repositories/public/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/maven-metadata.xml
    https://oss.sonatype.org/content/repositories/public/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.pom
    https://oss.sonatype.org/content/repositories/public/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.jar
    http://repo.spongepowered.org/maven/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/maven-metadata.xml
    http://repo.spongepowered.org/maven/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.pom
    http://repo.spongepowered.org/maven/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.jar
    file:/home/babs/.gradle/caches/minecraft/deobfedDeps/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/maven-metadata.xml
    file:/home/babs/.gradle/caches/minecraft/deobfedDeps/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.pom
    file:/home/babs/.gradle/caches/minecraft/deobfedDeps/deobf/net/malisis/malisiscore/1.11.2-5.0.2-SNAPSHOT/malisiscore-1.11.2-5.0.2-SNAPSHOT.jar
    file:/home/babs/Stuff/CubicChunks/.gradle/minecraft/malisiscore-1.11.2-5.0.2-SNAPSHOT.jar
    file:/home/babs/Stuff/CubicChunks/.gradle/minecraft/malisiscore.jar
Required by:
    project :
	at org.gradle.internal.resolve.result.DefaultBuildableComponentResolveResult.notFound(DefaultBuildableComponentResolveResult.java:38)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolveModule(RepositoryChainComponentMetaDataResolver.java:88)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolve(RepositoryChainComponentMetaDataResolver.java:59)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.ComponentResolversChain$ComponentMetaDataResolverChain.resolve(ComponentResolversChain.java:85)
	at org.gradle.api.internal.artifacts.ivyservice.clientmodule.ClientModuleResolver.resolve(ClientModuleResolver.java:45)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$ModuleVersionResolveState.resolve(DependencyGraphBuilder.java:661)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$ModuleVersionResolveState.getMetaData(DependencyGraphBuilder.java:672)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$DependencyEdge.calculateTargetConfigurations(DependencyGraphBuilder.java:297)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$DependencyEdge.attachToTargetConfigurations(DependencyGraphBuilder.java:270)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.traverseGraph(DependencyGraphBuilder.java:167)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:104)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:92)
	at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver$1.run(CacheLockingArtifactDependencyResolver.java:45)
	at org.gradle.internal.Factories$1.create(Factories.java:25)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:190)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:172)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:136)
	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:199)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultCacheLockingManager.useCache(DefaultCacheLockingManager.java:60)
	at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver.resolve(CacheLockingArtifactDependencyResolver.java:43)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolveGraph(DefaultConfigurationResolver.java:130)
	at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:74)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:67)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$3.execute(DefaultConfiguration.java:457)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$3.execute(DefaultConfiguration.java:449)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:449)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:425)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:417)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:213)
	at org.gradle.internal.metaobject.BeanDynamicObject.getProperty(BeanDynamicObject.java:156)
	at org.gradle.internal.metaobject.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:55)
	at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:60)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getProperty(Unknown Source)
	... 78 more


BUILD FAILED

Total time: 4.161 secs

```

**Comment by Niko-sk2x** [comment]
It's ForgeGradle bug, run `./gradlew setup(Decomp|Ci|Dev)Workspace`\* before building it, see https://github.com/MinecraftForge/ForgeGradle/issues/410

\* - only one of them, like `./gradlew setupDecompWorkspace`
