### ISSUE TITLE
Extreme fog after clouds

### ISSUE THREAD

**Issue by ghost** [Barteks2x/CubicChunks#184]
For some reason when I get higher than the clouds on clouds fancy and fast, there is extreme amount of fog everywhere. If I close the clouds, the fog is everywhere.

**Comment by Niko-sk2x** [comment]
Screenshots? And log.

**Comment by ModForge** [comment]
![2017-05-21_16 10 41](https://cloud.githubusercontent.com/assets/16163271/26284287/1842421a-3e40-11e7-9cd1-64d09a2c2067.png)
![2017-05-21_16 10 47](https://cloud.githubusercontent.com/assets/16163271/26284289/188252a6-3e40-11e7-8199-e1296e2ec1e2.png)
![2017-05-21_16 10 31](https://cloud.githubusercontent.com/assets/16163271/26284290/18850122-3e40-11e7-8eeb-9eace6ebc368.png)
![2017-05-21_16 10 36](https://cloud.githubusercontent.com/assets/16163271/26284288/186b2a0e-3e40-11e7-881b-8520b8dc32a7.png)

**Comment by ModForge** [comment]
Seems like this only happens when BetterFps is installed

**Comment by Niko-sk2x** [comment]
...
**ALWAYS** give information about all other mod syou have installed and **full client and/or server log** when you report  a bug. 

This is most likely BetterFPS patching something in a strange way.

**Comment by ModForge** [comment]
Do you still want me to put the latest.log file?

**Comment by ModForge** [comment]
It also only happens when the "Vanilla algorithm" is selected

**Comment by Niko-sk2x** [comment]
Which exact mod version is it? And yes, include the log.

**Comment by ModForge** [comment]
Wait I also tried to set the fog to fast and it happened even without the vanilla algorithm

**Comment by ModForge** [comment]
Seems like it was not the vanilla algorithms problem

**Comment by Niko-sk2x** [comment]
Still, i want full CubicChunks version (ideally commit hash) and log.

**Comment by ModForge** [comment]
versions 1.4.4

**Comment by ModForge** [comment]
cubic chunk versions is 0.0.530.0

**Comment by Niko-sk2x** [comment]
...
Cubic Chunks version.

**Comment by ModForge** [comment]
[16:40:18] [Client thread/INFO]: Setting user: ModForge
[16:40:20] [Client thread/WARN]: Skipping bad option: lastServer:
[16:40:20] [Client thread/INFO]: LWJGL Version: 2.9.4
[16:40:21] [Client thread/INFO]: [STDOUT]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  CubicChunksCoreMod (CubicChunks-1.11.2-0.0.530.0.jar)
  MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 5/21/17 4:40 PM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 498166608 bytes (475 MB) / 813170688 bytes (775 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
CubicChunksCoreMod (CubicChunks-1.11.2-0.0.530.0.jar)
  
MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.92' Renderer: 'GeForce GTX 750/PCIe/SSE2'
[16:40:23] [Client thread/INFO]: Reloading ResourceManager: BetterFps, Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:CubicChunks, FMLFileResourcePack:MalisisCore
[16:40:24] [Sound Library Loader/INFO]: Starting up SoundSystem...
[16:40:24] [Thread-8/INFO]: Initializing LWJGL OpenAL
[16:40:24] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[16:40:24] [Thread-8/INFO]: OpenAL initialized.
[16:40:25] [Sound Library Loader/INFO]: Sound engine started
[16:40:26] [Client thread/INFO]: Created: 16x16 textures-atlas
[16:40:26] [Client thread/INFO]: Reloading ResourceManager: BetterFps, Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:CubicChunks, FMLFileResourcePack:MalisisCore
[16:40:26] [Client thread/INFO]: SoundSystem shutting down...
[16:40:27] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[16:40:27] [Sound Library Loader/INFO]: Starting up SoundSystem...
[16:40:27] [Thread-10/INFO]: Initializing LWJGL OpenAL
[16:40:27] [Thread-10/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[16:40:27] [Thread-10/INFO]: OpenAL initialized.
[16:40:27] [Sound Library Loader/INFO]: Sound engine started
[16:40:29] [Client thread/INFO]: Created: 512x512 textures-atlas
[16:40:30] [Client thread/WARN]: Skipping bad option: lastServer:
[16:40:31] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[16:41:12] [Server thread/INFO]: Starting integrated minecraft server version 1.11.2
[16:41:12] [Server thread/INFO]: Generating keypair
[16:41:14] [Server thread/INFO]: Preparing start region for level 0
[16:41:15] [Server thread/INFO]: Changing view distance to 16, from 10
[16:41:15] [Server thread/INFO]: ModForge[local:E:cfdc0227] logged in with entity id 239 at (-344.3806513675611, 144.11829109607035, 190.50664217114408)
[16:41:15] [Server thread/INFO]: ModForge joined the game
[16:41:17] [Server thread/INFO]: Saving and pausing game...
[16:41:17] [Server thread/INFO]: Saving chunks for level 'Yeni Dünya'/Overworld
[16:41:17] [Server thread/INFO]: Saving chunks for level 'Yeni Dünya'/Nether
[16:41:17] [Server thread/INFO]: Saving chunks for level 'Yeni Dünya'/The End
[16:41:17] [pool-2-thread-1/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@fb4a628[id=d4ff6d71-5c93-3dc2-8fea-2b5d1fc67813,name=ModForge,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[YggdrasilAuthenticationService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [YggdrasilMinecraftSessionService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:60) [YggdrasilMinecraftSessionService$1.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:57) [YggdrasilMinecraftSessionService$1.class:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) [guava-17.0.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:170) [YggdrasilMinecraftSessionService.class:?]
	at net.minecraft.client.Minecraft.func_181037_M(Minecraft.java:2903) [bes.class:?]
	at net.minecraft.client.resources.SkinManager$3.run(SourceFile:110) [cag$3.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_131]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[16:41:22] [Server thread/INFO]: Saving and pausing game...
[16:41:22] [Server thread/INFO]: Saving chunks for level 'Yeni Dünya'/Overworld
[16:41:22] [Server thread/INFO]: Saving chunks for level 'Yeni Dünya'/Nether
[16:41:22] [Server thread/INFO]: Saving chunks for level 'Yeni Dünya'/The End
[16:41:23] [Server thread/INFO]: Stopping server
[16:41:23] [Server thread/INFO]: Saving players
[16:41:23] [Server thread/INFO]: ModForge lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[16:41:23] [Server thread/INFO]: ModForge left the game
[16:41:23] [Server thread/INFO]: Stopping singleplayer server as player logged out
[16:41:23] [Server thread/INFO]: Saving worlds
[16:41:23] [Server thread/INFO]: Saving chunks for level 'Yeni Dünya'/Overworld
[16:41:23] [Server thread/INFO]: Saving chunks for level 'Yeni Dünya'/Nether
[16:41:23] [Server thread/INFO]: Saving chunks for level 'Yeni Dünya'/The End

**Comment by ModForge** [comment]
√

**Comment by Niko-sk2x** [comment]
Are you sure this only happens with BetterFPS?

**Comment by ModForge** [comment]
I have only malisiscore cubicchunks and betterfps installed. But it happens when the fog is set to fast.

**Comment by ModForge** [comment]
What about the algorithms? Some of them seems like they are adding extra lag with cubicchunks

**Comment by Niko-sk2x** [comment]
VanillaCubic is literally just vanilla generator filled with stone below y=0. FllatCubic is cubic chunks version of superflat. CustomCubic is customizable cubic chunks world, that actually does peoper cubic chunks terrain. Remove BetterFPS first. And test again.

**Comment by ModForge** [comment]
I was talking about betterfps algorithms

**Comment by Niko-sk2x** [comment]
oh... I haven't used betterfps. You got me very confused here.

**Comment by ModForge** [comment]
It does not appear without betterfps

**Comment by ModForge** [comment]
Maybe I should create this issue on betterfps github page

**Comment by Niko-sk2x** [comment]
Strange things are going to happen with non-vanilla fog algorithms because currently I use very confusing hack to make the fog disabled below y=0.

The relevant part in vanilla code looks like this:

```java
        double d1 = (entity.lastTickPosY + (entity.posY - entity.lastTickPosY) * (double)partialTicks) * world.provider.getVoidFogYFactor();

        if (entity instanceof EntityLivingBase && ((EntityLivingBase)entity).isPotionActive(MobEffects.BLINDNESS)) {
            int i = ((EntityLivingBase)entity).getActivePotionEffect(MobEffects.BLINDNESS).getDuration();

            if (i < 20) {
                d1 *= (double)(1.0F - (float)i / 20.0F);
            }
            else {
                d1 = 0.0D;
            }
        }

        if (d1 < 1.0D) {
            if (d1 < 0.0D) {
                d1 = 0.0D;
            }

            d1 = d1 * d1;
            // this makes the fog appear
            this.fogColorRed = (float)((double)this.fogColorRed * d1);
            this.fogColorGreen = (float)((double)this.fogColorGreen * d1);
            this.fogColorBlue = (float)((double)this.fogColorBlue * d1);
        }
```

Below y=0 the value `d1` will always be negative, no matter how large value I give for `getVoidFogYFactor()` which is the only thing I directly control there. Unless I return value `NaN` (not a number). Then `d1` will also be `NaN`. `NaN` has the special property that if you compare it to anything *including itself* it will always be false except when comparing for not-equal). This means that the whole `d1 < 1.0D` part will be skipped and no y-based fog distance decreasing will occur.

All it takes to break it is a slight change in the algorithm. I don't see any way for me to fix it. Even if I modify that part of code to do it peoperly, non-vanilla algrithms still won't work.

Even further, BetterFPS might assume that there is nothing above y=256 so the fog can be more dense there.

Anyway all of that is my speculation until I actually debug it. And I can't because BetterFPS doesn't work in dev environment.

**Comment by Niko-sk2x** [comment]
Fixed by BetterFPS. Just wait for new release now.

**Comment by Niko-sk2x** [comment]
Note that this was also a BetterFPS issue without CubicChunks. Which I would have known if I actually tested it myself.
