### ISSUE TITLE
Random ConcurrentModificationException when updating player entity near BuildCraft quarry frame when part of the frame gets unloaded

### ISSUE THREAD

**Issue by Niko-sk2x** [Barteks2x/CubicChunks#190]
```
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:212) ~[NetworkSystem.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:818) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:699) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156) ~[IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$SubList$1.checkForComodification(ArrayList.java:1205) ~[?:1.8.0_131]
	at java.util.ArrayList$SubList$1.next(ArrayList.java:1106) ~[?:1.8.0_131]
	at net.minecraft.world.chunk.Chunk.handler$getEntitiesWithinAABBForEntity_CubicChunks$zzk000(Chunk.java:2279) ~[Chunk.class:?]
	at net.minecraft.world.chunk.Chunk.getEntitiesWithinAABBForEntity(Chunk.java) ~[Chunk.class:?]
	at net.minecraft.world.World.getEntitiesInAABBexcluding(World.java:3216) ~[World.class:?]
	at net.minecraft.world.World.getEntitiesWithinAABBExcludingEntity(World.java:3196) ~[World.class:?]
	at net.minecraft.world.World.getCollisionBoxes(World.java:1469) ~[World.class:?]
	at net.minecraft.entity.Entity.move(Entity.java:816) ~[Entity.class:?]
	at net.minecraft.entity.EntityLivingBase.moveEntityWithHeading(EntityLivingBase.java:2065) ~[EntityLivingBase.class:?]
	at net.minecraft.entity.player.EntityPlayer.moveEntityWithHeading(EntityPlayer.java:1954) ~[EntityPlayer.class:?]
	at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2504) ~[EntityLivingBase.class:?]
	at net.minecraft.entity.player.EntityPlayer.onLivingUpdate(EntityPlayer.java:566) ~[EntityPlayer.class:?]
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2296) ~[EntityLivingBase.class:?]
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:259) ~[EntityPlayer.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:368) ~[EntityPlayerMP.class:?]
	at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:176) ~[NetHandlerPlayServer.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:218) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:309) ~[NetworkManager.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:197) ~[NetworkSystem.class:?]
	... 5 more
```

**Comment by Niko-sk2x** [comment]
After the one time it happened I wasn't able to reproduce it so closing for now.
