### ISSUE TITLE
Adding already existing cube to column

### ISSUE THREAD

**Issue by Niko-sk2x** [Barteks2x/CubicChunks#195]
```
java.lang.IllegalArgumentException: Cube at 12 already exists!
    at cubicchunks.world.column.CubeMap.put(CubeMap.java:72)
    at net.minecraft.world.chunk.Chunk.addCube(Chunk.java:2782)
    at cubicchunks.server.CubeProviderServer.onCubeLoaded(CubeProviderServer.java:309)
    at cubicchunks.server.CubeProviderServer.getCube(CubeProviderServer.java:289)
    at cubicchunks.server.CubeProviderServer.getCube(CubeProviderServer.java:220)
    at net.minecraft.world.chunk.Chunk.getEBS_CubicChunks(Chunk.java:1809)
    at net.minecraft.world.chunk.Chunk.redirect$getLightSubtracted_CubicChunks_EBSGetRedirect$zzk000(Chunk.java:2140)
    at net.minecraft.world.chunk.Chunk.getLightSubtracted(Chunk.java:728)
    at net.minecraft.world.World.getLight(World.java:788)
    at net.minecraft.world.World.getLight(World.java:749)
    at net.minecraft.world.World.getLightFromNeighbors(World.java:739)
    at net.minecraft.block.BlockGrass.updateTick(BlockGrass.java:45)
    at net.minecraft.block.Block.randomTick(Block.java:605)
    at net.minecraft.world.WorldServer.updateBlocks(WorldServer.java:493)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:228)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:784)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:699)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by Secretname2009** [comment]
I hosted a LAN server with 0.0.822.0 but when the second player logged in somewhere else but not too close to me, this crash happened:
[crash-2018-02-01_19.11.45-server.txt](https://github.com/OpenCubicChunks/CubicChunks/files/1686668/crash-2018-02-01_19.11.45-server.txt)

EDIT: Nevermind, i just noticed that this error kept happening randomly over time and if it got bad then it would freeze or crash like above, the cause to my crash seems to be Journeymap Mod
