### ISSUE TITLE
Starting Minecraft with Mod in mods folder crashed before forge loads

### ISSUE THREAD

**Issue by GalHorowitz** [Barteks2x/CubicChunks#383]
When I open Minecraft with forge it loads up, displays all the loading bars for forge and then the main menu shows up.
If I put the mod jar in the mods folder, the game doesnt even open up the game window with the loading bars and crashes immediately. Logs:
```[15:00:48] [main/DEBUG] [FML]:   Adding CubicChunks.jar to the mod list
[15:00:48] [main/DEBUG] [FML]: Examining for coremod candidacy CubicChunks.jar
[15:00:48] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from CubicChunks.jar
[15:00:48] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:00:48] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[15:00:48] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[15:00:48] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[15:00:48] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[15:00:48] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[15:00:48] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[15:00:48] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[15:00:48] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[15:00:48] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)```

**Comment by Foghrye4** [comment]
Where did you get 'CubicChunks.jar'?

**Comment by GalHorowitz** [comment]
I built it from the repo and just took the CubicChunks-1.12.2-0.0.853.0-SNAPSHOT.jar and renamed it. @Foghrye4

**Comment by Foghrye4** [comment]
@GalHorowitz you should've used `CubicChunks-1.12.2-0.0.853.0-SNAPSHOT-all.jar` not `CubicChunks-1.12.2-0.0.853.0-SNAPSHOT.jar`
A second one contain no necessary external libraries. Only CubicChunks code.
