### ISSUE TITLE
Potential incompatibility with Dynamic Surroundings

### ISSUE THREAD

**Issue by asiekierka** [Barteks2x/CubicChunks#386]
```java.lang.ArrayIndexOutOfBoundsException: -1073741824
    at net.minecraft.world.ChunkCache.getLightForExt(ChunkCache.java:133)
    at net.minecraft.world.ChunkCache.getCombinedLight(ChunkCache.java:79)
    at org.blockartistry.lib.chunk.PassThroughChunkCache.getCombinedLight(PassThroughChunkCache.java:108)
    at org.blockartistry.DynSurround.client.fx.particle.mote.MoteParticle.getBrightnessForRender(MoteParticle.java:160)
    at org.blockartistry.DynSurround.client.fx.particle.mote.MoteParticle.updateBrightness(MoteParticle.java:110)
    at org.blockartistry.DynSurround.client.fx.particle.mote.MoteParticle.onUpdate(MoteParticle.java:102)
    at org.blockartistry.DynSurround.client.fx.particle.mote.MoteAgeable.onUpdate(MoteAgeable.java:58)
    at org.blockartistry.DynSurround.client.fx.particle.mote.ParticleCollection.lambda$static$0(ParticleCollection.java:56)
    at org.blockartistry.lib.collections.ObjectArray.removeIf(ObjectArray.java:79)
    at org.blockartistry.DynSurround.client.fx.particle.mote.ParticleCollection.onUpdate(ParticleCollection.java:112)
    at net.minecraft.client.particle.ParticleManager.tickParticle(ParticleManager.java:238)
    at net.minecraft.client.particle.ParticleManager.tickParticleList(ParticleManager.java:224)
    at net.minecraft.client.particle.ParticleManager.updateEffectLayer(ParticleManager.java:208)
    at net.minecraft.client.particle.ParticleManager.updateEffects(ParticleManager.java:164)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1900)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1097)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3940)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)```

**Comment by Niko-sk2x** [comment]
Did it crash? If it didn't, it should be fine. ChunkCache is modified my CC.

**Comment by Rongmario** [comment]
https://github.com/OreCruncher/DynamicSurroundings/issues/229
https://github.com/OreCruncher/DynamicSurroundings/issues/330

Edit: My bad, looks like a new crash

**Comment by asiekierka** [comment]
It did crash, or at least VanillaFix caught it as a crash.

**Comment by Dinolek** [comment]
You need to disable DS caching in config after [this commit](https://github.com/OreCruncher/DynamicSurroundings/commit/137d154067ba021b1a0132c936fc710cd8f30937#diff-3ec19ceab033b0768f326b8a58165e29R63).
[This ](https://github.com/OreCruncher/DynamicSurroundings/blob/master/src/main/java/org/blockartistry/lib/compat/ModEnvironment.java#L69)line is not used anymore after this.

**Comment by pressRtowin** [comment]
This issue is still open, as a new (or previously unmentioned bug) has arisen that causes the world to hang indefinitely when entering the nether with both CC and DS. I've commented on the corresponding issue at DS here: https://github.com/OreCruncher/DynamicSurroundings/issues/229

**Comment by Niko-sk2x** [comment]
I've seen it. It's unlikely there is anything I can do about it, but I will have to see what causes it.

**Comment by MrLightningBlaze** [comment]
So, running `Forge 14.2.3.5.2847` and `Cubic Chunks 0.0.1003.0-SNAPSHOT-all` with `dynamic surroundings 3.5.4.3` I have seen no sign of this issue whatsoever and did absoultely no config whatsoever, is it fixed?

**Comment by Niko-sk2x** [comment]
There have been reports of severe performance issues in the nether. I'm not sure about configuration.

**Comment by MrLightningBlaze** [comment]
I have noticed 0 drop in FPS or increase in CPU or RAM usage in the nether beyond what is expected (due to the amount of lava lighting in the nether), all with default Dynamic Surroundings config and essentially default CubicChunks config (A few modded dims in the blacklist), I can not speak for everyone, but I have not noticed preformance issues with it
