### ISSUE TITLE
IllegalArgumentException on world load

### ISSUE THREAD

**Issue by sirsavary** [Barteks2x/CubicChunks#41]
Zip of world: https://mega.nz/#!GU1lnbjQ!Fp5Z5YmM91WOl8p5oRs_gE9KDzMFXq19SCMFsKW7vGc
Stacktrace:
```
net.minecraft.util.ReportedException: Ticking memory connection
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:210) ~[NetworkSystem.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:806) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:687) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156) ~[IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
Caused by: java.lang.IllegalArgumentException: minY > maxY (65 > 64)
	at cubicchunks.world.cube.Cube$LightUpdateData.queueLightUpdate(Cube.java:531) ~[Cube$LightUpdateData.class:?]
	at cubicchunks.lighting.LightingManager.queueDiffuseUpdate(LightingManager.java:74) ~[LightingManager.class:?]
	at cubicchunks.lighting.LightingManager.columnSkylightUpdate(LightingManager.java:59) ~[LightingManager.class:?]
	at cubicchunks.server.chunkio.IONbtReader.readLightingInfo(IONbtReader.java:255) ~[IONbtReader.class:?]
	at cubicchunks.server.chunkio.IONbtReader.readCube(IONbtReader.java:115) ~[IONbtReader.class:?]
	at cubicchunks.server.chunkio.CubeIO.loadCubeAndAddToColumn(CubeIO.java:170) ~[CubeIO.class:?]
	at cubicchunks.server.ServerCubeCache.loadCube(ServerCubeCache.java:348) ~[ServerCubeCache.class:?]
	at cubicchunks.server.ServerCubeCache.loadCube(ServerCubeCache.java:388) ~[ServerCubeCache.class:?]
	at cubicchunks.world.dependency.DependencyManager.register(DependencyManager.java:122) ~[DependencyManager.class:?]
	at cubicchunks.worldgen.dependency.DependentCubeManager.register(DependentCubeManager.java:75) ~[DependentCubeManager.class:?]
	at cubicchunks.worldgen.WorldGenerator.generateCube(WorldGenerator.java:156) ~[WorldGenerator.class:?]
	at cubicchunks.worldgen.WorldGenerator.generateCube(WorldGenerator.java:172) ~[WorldGenerator.class:?]
	at cubicchunks.server.ServerCubeCache.loadCube(ServerCubeCache.java:369) ~[ServerCubeCache.class:?]
	at cubicchunks.server.ServerCubeCache.loadCube(ServerCubeCache.java:388) ~[ServerCubeCache.class:?]
	at cubicchunks.world.dependency.DependencyManager.register(DependencyManager.java:122) ~[DependencyManager.class:?]
	at cubicchunks.worldgen.dependency.DependentCubeManager.register(DependentCubeManager.java:75) ~[DependentCubeManager.class:?]
	at cubicchunks.worldgen.WorldGenerator.generateCube(WorldGenerator.java:156) ~[WorldGenerator.class:?]
	at cubicchunks.worldgen.WorldGenerator.generateCube(WorldGenerator.java:172) ~[WorldGenerator.class:?]
	at cubicchunks.server.ServerCubeCache.loadCube(ServerCubeCache.java:340) ~[ServerCubeCache.class:?]
	at cubicchunks.server.ServerCubeCache.loadCube(ServerCubeCache.java:384) ~[ServerCubeCache.class:?]
	at cubicchunks.server.PlayerCubeMapEntry.<init>(PlayerCubeMapEntry.java:71) ~[PlayerCubeMapEntry.class:?]
	at cubicchunks.server.PlayerCubeMap.getOrCreateCubeWatcher(PlayerCubeMap.java:304) ~[PlayerCubeMap.class:?]
	at cubicchunks.server.PlayerCubeMap.lambda$addPlayer$6(PlayerCubeMap.java:366) ~[PlayerCubeMap.class:?]
	at cubicchunks.visibility.CuboidalCubeSelector.forAllVisibleFrom(CuboidalCubeSelector.java:43) ~[CuboidalCubeSelector.class:?]
	at cubicchunks.server.PlayerCubeMap.addPlayer(PlayerCubeMap.java:362) ~[PlayerCubeMap.class:?]
	at net.minecraft.server.management.PlayerList.preparePlayer(PlayerList.java:310) ~[PlayerList.class:?]
	at net.minecraft.server.management.PlayerList.playerLoggedIn(PlayerList.java:389) ~[PlayerList.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:171) ~[PlayerList.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:263) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:212) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:308) ~[NetworkManager.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:195) ~[NetworkSystem.class:?]
	... 5 more
```

**Comment by Barteks2x** [comment]
Is this old world? Or newly generated?

**Comment by sirsavary** [comment]
Newly generated. Crashed because of an NPE, added "-XX:-OmitStackTraceInFastThrow" to my JVM args so I could get a stacktrace, now instantly crashing with this error on world load.

**Comment by Barteks2x** [comment]
Do you have seed? Might be easier to debug this way.

**Comment by Barteks2x** [comment]
NPE crash that is fices by this? Seems like PlayerChunkMap crash. These are bad. The first occurrence of this NPE should have fuill stacktrace.

**Comment by sirsavary** [comment]
I'll try and grab the seed, it was randomly generated. I didn't get a full stacktrace when it crashed originally.

**Comment by Barteks2x** [comment]
It probably crashed started throwing them every tick. If it spammed your console with them - look for the first one in old logs. It should have full stacktrace.

**Comment by Barteks2x** [comment]
The crash you are experiencing now is likely due to world corruption, but even that shouldn't happen. I didn't touch the code for a long time, but as I recall - there is no way these values could get into light update queue to be saved to NBT in the first place.

**Comment by sirsavary** [comment]
Went through the logs folder and I can't seem to find the client log, looks like it was deleted (it looks like Forge is only keeping the 3 most recent).

Seed for the world is 1411267924876177193

**Comment by Barteks2x** [comment]
Looks like I just got the same issue myself with my world.

**Comment by sirsavary** [comment]
If there's anything I can do to help, just let me know. Once I'm more familiar with Cubic Chunks internals I can probably be more useful.

**Comment by Barteks2x** [comment]
I hope so. Now I think I should write more comments in my code... I can't figure out how the code was supposed to work.
