### ISSUE TITLE
Dependency system sometimes throws exceptions when generating new cubes after reloading world.

### ISSUE THREAD

**Issue by Barteks2x** [Barteks2x/CubicChunks#43]
The error is:
```
java.lang.NullPointerException
    at cubicchunks.world.dependency.RequiredCube.setTargetStage(RequiredCube.java:96) ~[RequiredCube.class:?]
    at cubicchunks.world.dependency.DependencyManager.register(DependencyManager.java:101) ~[DependencyManager.class:?]
    at cubicchunks.worldgen.dependency.DependentCubeManager.register(DependentCubeManager.java:75) ~[DependentCubeManager.class:?]
//and so on
````
(full stacktrace: http://pastebin.com/5D2pHYzD)

This causes holes in the world, because forge ignores these exceptions.

The reason is that some cubes that it uses are not loaded yet.

**Comment by Barteks2x** [comment]
It's still caused by #41 and the fact that dependency system assumes that loading chunks never fails.
