### ISSUE TITLE
Too old forge version

### ISSUE THREAD

**Issue by WillH2** [Barteks2x/CubicChunks#437]
Hello! I have been trying for the last few days to get these two mods (cubic world gen and cubic chunks) to work for minecraft 1.12.2, i have downloaded other mods for 1.12.2 and they work fine they are:
1. Ambient sounds mod
However, every time i run minecraft with these two mods in it crashes a second after the forge screen pops up
I have looked everywhere on the internet and have not found a solution to my problem as i am using the correct mod version and the correct forge version
Thanks for the help, bye

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all (2).jar)
  CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.39.0-SNAPSHOT-all (2).jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 4/15/19 7:44 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraftforge.fml.common.versioning.ComparableVersion.parseVersion(ComparableVersion.java:371)
	at net.minecraftforge.fml.common.versioning.ComparableVersion.<init>(ComparableVersion.java:362)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:31)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:42)
	at net.minecraftforge.fml.common.FMLModContainer.getProcessedVersion(FMLModContainer.java:625)
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:235)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:547)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:227)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.versioning.ComparableVersion.parseVersion(ComparableVersion.java:371)
	at net.minecraftforge.fml.common.versioning.ComparableVersion.<init>(ComparableVersion.java:362)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:31)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:42)
	at net.minecraftforge.fml.common.FMLModContainer.getProcessedVersion(FMLModContainer.java:625)
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:235)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:547)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:227)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 505728896 bytes (482 MB) / 771751936 bytes (736 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2486 8 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version                   | Source                                             | Signature                                |
	|:----- |:----------------- |:------------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| U     | minecraft         | 1.12.2                    | minecraft.jar                                      | None                                     |
	| U     | mcp               | 9.42                      | minecraft.jar                                      | None                                     |
	| U     | FML               | 8.0.99.99                 | forge-1.12.2-14.23.0.2486.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | forge             | 14.23.0.2486              | forge-1.12.2-14.23.0.2486.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UD    | cubicchunkscore   | @@VERSION@@               | minecraft.jar                                      | None                                     |
	| U     | mercurius_updater | 1.0                       | MercuriusUpdater-1.12.2.jar                        | None                                     |
	| U     | cubicchunks       | 1.12.2-0.0.926.0-SNAPSHOT | CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all (2).jar  | None                                     |
	| U     | cubicgen          | null                      | CubicWorldGen-1.12.2-0.0.39.0-SNAPSHOT-all (2).jar | None                                     |

	Loaded coremods (and transformers): 
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.926.0-SNAPSHOT-all (2).jar)
  
CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.39.0-SNAPSHOT-all (2).jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13537 Compatibility Profile Context 24.20.13001.1010' Renderer: 'Radeon RX 580 Series'
	Launched Version: 1.12.2-forge1.12.2-14.23.0.2486
	LWJGL: 2.9.4
	OpenGL: Radeon RX 580 Series GL version 4.5.13537 Compatibility Profile Context 24.20.13001.1010, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz

**Comment by Niko-sk2x** [comment]
You somehow managed to get forge version so old it doesn't get to the information screen where it tells you that you have too old forge version, because it doesn't yet support the version string format that I used. Update forge and it will work.

**Comment by WillH2** [comment]
Thank you
