### ISSUE TITLE
aether(2) support?

### ISSUE THREAD

**Issue by anonymous2007** [Barteks2x/CubicChunks#470]
the aether 2 (which is still in development) .does not seem to be compatible. i believe it has something to do with chunks and worldgen. i am pretty sure it has to do with aether and cubicchunks, as this only happened once i installed cubic chunks and the loader only crashed when it got to the aether.

crash report:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
  GenderLoadingPlugin ([1.12.2]Gender-1.2.9.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.970.0-SNAPSHOT-all.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 11/6/19 3:46 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/world/chunk/Chunk
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/chunk/Chunk
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:128)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:112)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 37 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.chunk.Chunk
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 811140008 bytes (773 MB) / 1140850688 bytes (1088 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 44 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version                   | Source                                             | Signature                                |
	|:----- |:-------------------------------------------- |:------------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                                    | 1.12.2                    | minecraft.jar                                      | None                                     |
	| LC    | mcp                                          | 9.42                      | minecraft.jar                                      | None                                     |
	| LC    | FML                                          | 8.0.99.99                 | forge-1.12.2-14.23.5.2838.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                                        | 14.23.5.2838              | forge-1.12.2-14.23.5.2838.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | com.elytradev.movingworld.common.asm.coremod |                           | minecraft.jar                                      | None                                     |
	| LC    | gender                                       | 1.2.9                     | [1.12.2]Gender-1.2.9.jar                           | None                                     |
	| LC    | orbis-lib                                    | 0.2.0                     | orbis-lib-1.12.2-0.2.0+build127.jar                | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LE    | aether                                       | 0.2.6                     | aether_ii-1.12.2-0.2.6+build127-universal.jar      | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| L     | bibliocraft                                  | 2.4.5                     | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
	| L     | codechickenlib                               | 3.2.2.353                 | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | None                                     |
	| L     | redstoneflux                                 | 2.1.0                     | RedstoneFlux-1.12-2.1.0.6-universal.jar            | None                                     |
	| L     | brandonscore                                 | 2.4.17                    | BrandonsCore-1.12.2-2.4.17.208-universal.jar       | None                                     |
	| L     | chiselsandbits                               | 14.33                     | chiselsandbits-14.33.jar                           | None                                     |
	| L     | cofhcore                                     | 4.6.3                     | CoFHCore-1.12.2-4.6.3.27-universal.jar             | None                                     |
	| L     | cofhworld                                    | 1.3.1                     | CoFHWorld-1.12.2-1.3.1.7-universal.jar             | None                                     |
	| L     | computercraft                                | 1.80pr1                   | ComputerCraft1.80pr1.jar                           | None                                     |
	| L     | craftstudioapi                               | 1.0.0                     | CraftStudio-1.0.0.93-mc1.12-alpha.jar              | None                                     |
	| L     | cubicchunks                                  | 1.12.2-0.0.970.0-SNAPSHOT | CubicChunks-1.12.2-0.0.970.0-SNAPSHOT-all.jar      | None                                     |
	| L     | movingworld                                  | 1.12-6.342                | movingworld-1.12-6.342-full.jar                    | None                                     |
	| L     | davincisvessels                              | @DVESSELSVER@             | davincisvessels-1.12-6.340-full.jar                | None                                     |
	| L     | thermalfoundation                            | 2.6.3                     | ThermalFoundation-1.12.2-2.6.3.27-universal.jar    | None                                     |
	| L     | draconicevolution                            | 2.3.24                    | Draconic-Evolution-1.12.2-2.3.24.349-universal.jar | None                                     |
	| L     | llibrary                                     | 1.7.19                    | llibrary-1.7.19-1.12.2.jar                         | None                                     |
	| L     | dragonmounts                                 | 1.12.2-1.6.2              | DragonMounts2-1.12.2-1.6.2.jar                     | None                                     |
	| L     | infinity                                     | 0.13.2                    | Infinity-0.13.2.jar                                | None                                     |
	| L     | inventorypets                                | 2.0.3                     | inventorypets-1.12-2.0.3.jar                       | None                                     |
	| L     | ironchest                                    | 1.12.2-7.0.67.844         | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| L     | jei                                          | 4.15.0.268                | jei_1.12.2-4.15.0.268.jar                          | None                                     |
	| L     | malisiscore                                  | 1.12.2-6.5.1-SNAPSHOT     | malisiscore-1.12.2-6.5.1.jar                       | None                                     |
	| L     | malisisdoors                                 | 1.12.2-7.3.0              | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
	| L     | mobbattle                                    | 2.3.2                     | MobBattleMod-1.12.2-2.3.2.jar                      | None                                     |
	| L     | neat                                         | 1.4-17                    | Neat+1.4-17.jar                                    | None                                     |
	| L     | projectintelligence                          | 1.0.7                     | ProjectIntelligence-1.12.2-1.0.7.24-universal.jar  | None                                     |
	| L     | thermalexpansion                             | 5.5.4                     | ThermalExpansion-1.12.2-5.5.4.43-universal.jar     | None                                     |
	| L     | redstonearsenal                              | 2.6.3                     | RedstoneArsenal-1.12.2-2.6.3.18-universal.jar      | None                                     |
	| L     | refinedstorage                               | 1.6.15                    | refinedstorage-1.6.15.jar                          | None                                     |
	| L     | tammodized                                   | 0.15.6                    | TamModized-1.12.2.jar                              | None                                     |
	| L     | tektopia                                     | 1.1.0                     | tektopia-1.1.0.jar                                 | None                                     |
	| L     | thermalcultivation                           | 0.3.3                     | ThermalCultivation-1.12.2-0.3.3.12-universal.jar   | None                                     |
	| L     | thermaldynamics                              | 2.5.5                     | ThermalDynamics-1.12.2-2.5.5.21-universal.jar      | None                                     |
	| L     | thermalinnovation                            | 0.3.3                     | ThermalInnovation-1.12.2-0.3.3.12-universal.jar    | None                                     |
	| L     | voidcraft                                    | 0.26.10                   | VoidCraft-Mod-1.12.2.jar                           | None                                     |
	| L     | phosphor-lighting                            | 1.12.2-0.2.6              | phosphor-1.12.2-0.2.6+build50.jar                  | None                                     |
	| UD    | cubicchunkscore                              | @@VERSION@@               | minecraft.jar                                      | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
  
GenderLoadingPlugin ([1.12.2]Gender-1.2.9.jar)
  com.github.ipixeli.gender.coremod.GenderClassTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.970.0-SNAPSHOT-all.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1 ATI-2.11.20' Renderer: 'AMD Radeon RX 580 OpenGL Engine'
```

**Comment by Niko-sk2x** [comment]
This is a known issue - cubic chunks is incompatible with phosphor mod, which is bundled with aether 2. Removing phosphor makes aether 2 compatible, but it's also very hard for an average user to do (you have to remove it from the jar, edit MANIFEST.MF to remove contained dependency entry, and remove jar signature data from META-INF). I may do something about it in future version.

**Comment by anonymous2007** [comment]
ohh ok. i also reported this to the aether 2, so there may be an easier method.

thank you!

**Comment by Niko-sk2x** [comment]
They know about this issue. No need to report it. This can either be fixed on my side (I think it's possible), or with a bit of cooperation. But there is so much more to do that this is not high enough priority.
