### ISSUE TITLE
I can't launch the game.

### ISSUE THREAD

**Issue by teej1469** [Barteks2x/CubicChunks#486]
I am unable to launch the latest 1.12.2 version of the mod. When I launch the game, it loads, I get a frame of the main menu, and then it crashes. Here is the crash log:

[latest.log](https://github.com/OpenCubicChunks/CubicChunks/files/4392515/latest.log)

**Comment by teej1469** [comment]
> I am unable to launch the latest 1.12.2 version of the mod. When I launch the game, it loads, I get a frame of the main menu, and then it crashes. Here is the crash log:
> 
> [latest.log](https://github.com/OpenCubicChunks/CubicChunks/files/4392515/latest.log)

I have the crash report text here too if u want it.


---- Minecraft Crash Report ----

WARNING: coremods are present:
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 3/27/20 7:09 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/RenderGlobal
	at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:769)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:807)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.RenderGlobal
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 16 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method getMaxWorldHeight(I)I in cubicchunks.mixins.selectable.json:client.optifine.MixinRenderGlobalOptifine_E failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap cubicchunks.mixins.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 21 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:769)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:807)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 203975680 bytes (194 MB) / 771751936 bytes (736 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version                    | Source                                          | Signature                                |
	|:----- |:--------------- |:-------------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft       | 1.12.2                     | minecraft.jar                                   | None                                     |
	| UC    | mcp             | 9.42                       | minecraft.jar                                   | None                                     |
	| UC    | FML             | 8.0.99.99                  | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge           | 14.23.5.2768               | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | cubicchunkscore | 1.12.2-0.0.1055.0-SNAPSHOT | minecraft.jar                                   | None                                     |
	| UC    | cubicchunks     | 1.12.2-0.0.1055.0-SNAPSHOT | CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar  | None                                     |
	| UC    | cubicgen        | 1.12.2-0.0.126.0-SNAPSHOT  | CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar | None                                     |
	| UC    | lunatriuscore   | 1.2.0.42                   | LunatriusCore-1.12.2-1.2.0.42-universal.jar     | None                                     |
	| UC    | malisiscore     | 1.12.2-6.5.1-SNAPSHOT      | malisiscore-1.12.2-6.5.1.jar                    | None                                     |

	Loaded coremods (and transformers): 
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.cubicgen.asm.coremod.MapGenStrongholdCubicConstructorTransform
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.6911' Renderer: 'Intel(R) UHD Graphics'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics GL version 4.6.0 - Build 26.20.100.6911, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz

**Comment by teej1469** [comment]
Nvm fixed it. I moved my client-side 1.15.2 mods into a separate folder.

**Comment by Niko-sk2x** [comment]
Outdated forge and probably old optifine version.
