### ISSUE TITLE
Issue loading saved world (IllegalArgumentException)

### ISSUE THREAD

**Issue by hendog72** [Barteks2x/CubicChunks#490]
My son is the Minecraft player, I set up a 12.2 installation for him with just:
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar
  CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar
  terra121-0.1.jar

We continually crash trying to load an existing world he worked on for a few hours, new empty worlds start up fine. He said he was working on a pool in our virtual back yard. 

This is my 1st bug logged, I didn't see anyone reporting anything similar

Here's the Crash Report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar)
  CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 3/29/20 9:42 PM
Description: Exception ticking world

java.lang.IllegalArgumentException
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:334)
	at cubicchunks.regionlib.lib.Region.lambda$doReadKey$2(Region.java:151)
	at cubicchunks.regionlib.lib.Region$$Lambda$293/699189464.apply(Unknown Source)
	at java.util.Optional.flatMap(Optional.java:241)
	at cubicchunks.regionlib.lib.Region.doReadKey(Region.java:136)
	at cubicchunks.regionlib.lib.Region.lambda$readValue$1(Region.java:129)
	at cubicchunks.regionlib.lib.Region$$Lambda$292/2049076770.get(Unknown Source)
	at java.util.Optional.orElseGet(Optional.java:267)
	at cubicchunks.regionlib.lib.Region.readValue(Region.java:129)
	at cubicchunks.regionlib.api.storage.SaveSection.lambda$load$1(SaveSection.java:119)
	at cubicchunks.regionlib.api.storage.SaveSection$$Lambda$289/1722900606.apply(Unknown Source)
	at cubicchunks.regionlib.lib.provider.SharedCachedRegionProvider.fromRegion(SharedCachedRegionProvider.java:206)
	at cubicchunks.regionlib.lib.provider.SharedCachedRegionProvider.fromRegion(SharedCachedRegionProvider.java:77)
	at cubicchunks.regionlib.api.storage.SaveSection.load(SaveSection.java:119)
	at cubicchunks.regionlib.impl.SaveCubeColumns.load(SaveCubeColumns.java:96)
	at io.github.opencubicchunks.cubicchunks.core.server.chunkio.RegionCubeIO.loadCubeAsyncPart(RegionCubeIO.java:158)
	at io.github.opencubicchunks.cubicchunks.core.server.chunkio.async.forge.AsyncCubeIOProvider.run(AsyncCubeIOProvider.java:61)
	at io.github.opencubicchunks.cubicchunks.core.server.chunkio.async.forge.AsyncWorldIOExecutor.syncCubeLoad(AsyncWorldIOExecutor.java:122)
	at io.github.opencubicchunks.cubicchunks.core.server.CubeProviderServer.getCube(CubeProviderServer.java:311)
	at io.github.opencubicchunks.cubicchunks.core.server.CubeProviderServer.getCube(CubeProviderServer.java:244)
	at io.github.opencubicchunks.cubicchunks.core.server.CubeProviderServer.calculateDiffuseSkylight(CubeProviderServer.java:491)
	at io.github.opencubicchunks.cubicchunks.core.server.CubeProviderServer.postCubeLoadAttempt(CubeProviderServer.java:388)
	at io.github.opencubicchunks.cubicchunks.core.server.CubeProviderServer.getCube(CubeProviderServer.java:315)
	at io.github.opencubicchunks.cubicchunks.core.server.CubeWatcher.providePlayerCube(CubeWatcher.java:168)
	at io.github.opencubicchunks.cubicchunks.core.server.PlayerCubeMap.func_72693_b(PlayerCubeMap.java:379)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:334)
	at cubicchunks.regionlib.lib.Region.lambda$doReadKey$2(Region.java:151)
	at cubicchunks.regionlib.lib.Region$$Lambda$293/699189464.apply(Unknown Source)
	at java.util.Optional.flatMap(Optional.java:241)
	at cubicchunks.regionlib.lib.Region.doReadKey(Region.java:136)
	at cubicchunks.regionlib.lib.Region.lambda$readValue$1(Region.java:129)
	at cubicchunks.regionlib.lib.Region$$Lambda$292/2049076770.get(Unknown Source)
	at java.util.Optional.orElseGet(Optional.java:267)
	at cubicchunks.regionlib.lib.Region.readValue(Region.java:129)
	at cubicchunks.regionlib.api.storage.SaveSection.lambda$load$1(SaveSection.java:119)
	at cubicchunks.regionlib.api.storage.SaveSection$$Lambda$289/1722900606.apply(Unknown Source)
	at cubicchunks.regionlib.lib.provider.SharedCachedRegionProvider.fromRegion(SharedCachedRegionProvider.java:206)
	at cubicchunks.regionlib.lib.provider.SharedCachedRegionProvider.fromRegion(SharedCachedRegionProvider.java:77)
	at cubicchunks.regionlib.api.storage.SaveSection.load(SaveSection.java:119)
	at cubicchunks.regionlib.impl.SaveCubeColumns.load(SaveCubeColumns.java:96)
	at io.github.opencubicchunks.cubicchunks.core.server.chunkio.RegionCubeIO.loadCubeAsyncPart(RegionCubeIO.java:158)
	at io.github.opencubicchunks.cubicchunks.core.server.chunkio.async.forge.AsyncCubeIOProvider.run(AsyncCubeIOProvider.java:61)
	at io.github.opencubicchunks.cubicchunks.core.server.chunkio.async.forge.AsyncWorldIOExecutor.syncCubeLoad(AsyncWorldIOExecutor.java:122)
	at io.github.opencubicchunks.cubicchunks.core.server.CubeProviderServer.getCube(CubeProviderServer.java:311)
	at io.github.opencubicchunks.cubicchunks.core.server.CubeProviderServer.getCube(CubeProviderServer.java:244)
	at io.github.opencubicchunks.cubicchunks.core.server.CubeProviderServer.calculateDiffuseSkylight(CubeProviderServer.java:491)
	at io.github.opencubicchunks.cubicchunks.core.server.CubeProviderServer.postCubeLoadAttempt(CubeProviderServer.java:388)
	at io.github.opencubicchunks.cubicchunks.core.server.CubeProviderServer.getCube(CubeProviderServer.java:315)
	at io.github.opencubicchunks.cubicchunks.core.server.CubeWatcher.providePlayerCube(CubeWatcher.java:168)
	at io.github.opencubicchunks.cubicchunks.core.server.PlayerCubeMap.func_72693_b(PlayerCubeMap.java:379)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: Wilma Earth
	All players: 1 total; [EntityPlayerMP['sammmmyh'/54, l='Wilma Earth', x=4212627.39, y=55.86, z=-7140783.45]]
	Chunk stats: CubeProviderServer: 909 columns, 10867 cubes
	Level seed: -1168007088624159968
	Level generator: ID 11 - EarthCubic, ver 0. Features enabled: true
	Level generator options: {"projection":"equirectangular","orentation":"swapped","scaleX":100000.0,"scaleY":100000.0,"smoothblend":true,"roads":true,"customcubic":"","dynamicbaseheight":true,"osmwater":false,"buildings":false}
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 165487 game time, 60813 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 124293360 bytes (118 MB) / 805306368 bytes (768 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version                    | Source                                          | Signature |
	|:------ |:--------------- |:-------------------------- |:----------------------------------------------- |:--------- |
	| LCHIJA | minecraft       | 1.12.2                     | minecraft.jar                                   | None      |
	| LCHIJA | mcp             | 9.42                       | minecraft.jar                                   | None      |
	| LCHIJA | FML             | 8.0.99.99                  | forge-1.12.2-14.23.5.2847.jar                   | None      |
	| LCHIJA | forge           | 14.23.5.2847               | forge-1.12.2-14.23.5.2847.jar                   | None      |
	| LCHIJA | cubicchunkscore | 1.12.2-0.0.1055.0-SNAPSHOT | minecraft.jar                                   | None      |
	| LCHIJA | cubicchunks     | 1.12.2-0.0.1055.0-SNAPSHOT | CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar  | None      |
	| LCHIJA | cubicgen        | 1.12.2-0.0.126.0-SNAPSHOT  | CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar | None      |
	| LCHIJA | terra121        | 0.1                        | terra121-0.1.jar                                | None      |

	Loaded coremods (and transformers): 
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.cubicgen.asm.coremod.MapGenStrongholdCubicConstructorTransform
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CubicChunks WorldGen Hang Watchdog samples: (no data)
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['sammmmyh'/54, l='Wilma Earth', x=4212627.39, y=55.86, z=-7140783.45]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Niko-sk2x** [comment]
That looks like a corrupted world. While technically recoverable it requires special tools. Join CC discord for help (may not be immediately).

**Comment by hendog72** [comment]
I did read up on fixing a corrupted world by copying a few files from a new world, that did initially fix it. The world crashed one more time but now seems to be up and running.

**Comment by Niko-sk2x** [comment]
There are tools that can fix it by just removing corrupted chunk data. But there isn't really a good place to publish them anymore now that almost no-one uses minecraftforum.
