### ISSUE TITLE
Fix crash on removing player from world

### ISSUE THREAD

**Issue by NotStirred** [Barteks2x/CubicChunks#505]
CrashLog:
```
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.world.server.TicketManager.removePlayer(TicketManager.java:208) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:CubicChunks.mixins.core.json:common.ticket.MixinTicketManager,pl:mixin:APP:cubicchunks.mixins.access.json:common.TicketManagerAccess,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager.setPlayerTracking(ChunkManager.java:839) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:CubicChunks.mixins.core.json:common.chunk.MixinChunkManager,pl:mixin:APP:cubicchunks.mixins.access.json:common.ChunkManagerAccess,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager.untrack(ChunkManager.java:983) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:CubicChunks.mixins.core.json:common.chunk.MixinChunkManager,pl:mixin:APP:cubicchunks.mixins.access.json:common.ChunkManagerAccess,pl:mixin:A}
	at net.minecraft.world.server.ServerChunkProvider.untrack(ServerChunkProvider.java:450) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:CubicChunks.mixins.core.json:common.MixinServerChunkProvider,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.removeEntityComplete(ServerWorld.java:994) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.world.server.ServerWorld.removeEntity(ServerWorld.java:1038) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.world.server.ServerWorld.removePlayer(ServerWorld.java:1055) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.world.server.ServerWorld.removePlayer(ServerWorld.java:1051) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.server.management.PlayerList.playerLoggedOut(PlayerList.java:325) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.onDisconnect(ServerPlayNetHandler.java:943) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.network.NetworkManager.handleDisconnection(NetworkManager.java:421) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.tick(NetworkSystem.java:170) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:903) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:CubicChunks.mixins.core.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:821) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:CubicChunks.mixins.core.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:120) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:CubicChunks.mixins.core.json:common.MixinIntegratedServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:662) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:CubicChunks.mixins.core.json:common.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_252, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1307947536 bytes (1247 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 12
	JVM Flags: 8 total; -XX:+UseG1GC -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmluserdevclient
	ModLauncher naming: mcp
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.0_mapped_snapshot_20200520-1.15.1-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.0_mapped_snapshot_20200520-1.15.1-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.0_mapped_snapshot_20200520-1.15.1-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.0_mapped_snapshot_20200520-1.15.1-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.0_mapped_snapshot_20200520-1.15.1-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.0
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		client-extra.jar Minecraft {minecraft@1.15.2 DONE}
		forge-1.15.2-31.2.0_mapped_snapshot_20200520-1.15.1-recomp.jar Forge {forge@31.2.0 DONE}
		resources Cubic Chunks {cubicchunks@NONE DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['Dev'/1, l='New World (22) (4)', x=-244.41, y=122.15, z=124.41]]
	Data Packs: vanilla, mod:forge (incompatible), mod:cubicchunks (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
```

**Comment by NotStirred** [comment]
I believe fixed in a76cea0
