### ISSUE TITLE
Rare random crash when generating terrain

### ISSUE THREAD

**Issue by Barteks2x** [Barteks2x/CubicChunks#65]
It happened twice to me, once when I didn't expect it, second time when I tried to make it ctrash but set exception breakpoint to the wrong class:

```
net.minecraft.util.ReportedException: Exception ticking world
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:778) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:687) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156) ~[IntegratedServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
    at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapIterator.nextEntry(Int2ObjectOpenHashMap.java:511) ~[Int2ObjectOpenHashMap$MapIterator.class:?]
    at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueIterator.next(Int2ObjectOpenHashMap.java:706) ~[Int2ObjectOpenHashMap$ValueIterator.class:?]
    at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042) ~[?:1.8.0_91]
    at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042) ~[?:1.8.0_91]
    at cubicchunks.lighting.SkyLightUpdateCubeSelector.getCubesY(SkyLightUpdateCubeSelector.java:75) ~[SkyLightUpdateCubeSelector.class:?]
    at cubicchunks.lighting.LightingManager.columnSkylightUpdate(LightingManager.java:50) ~[LightingManager.class:?]
    at cubicchunks.world.column.Column.doOnBlockSetLightUpdates(Column.java:236) ~[Column.class:?]
    at cubicchunks.world.column.Column.setBlockState(Column.java:175) ~[Column.class:?]
    at net.minecraft.world.World.setBlockState(World.java:384) ~[World.class:?]
    at cubicchunks.worldgen.generator.custom.features.FeatureGenerator.setBlockOnly(FeatureGenerator.java:44) ~[FeatureGenerator.class:?]
    at cubicchunks.worldgen.generator.custom.features.trees.TreeGenerator.tryToPlaceDirtUnderTree(TreeGenerator.java:80) ~[TreeGenerator.class:?]
    at cubicchunks.worldgen.generator.custom.features.trees.SimpleTreeGenerator.canGenerateTree(SimpleTreeGenerator.java:84) ~[SimpleTreeGenerator.class:?]
    at cubicchunks.worldgen.generator.custom.features.trees.SimpleTreeGenerator.generateAt(SimpleTreeGenerator.java:58) ~[SimpleTreeGenerator.class:?]
    at cubicchunks.worldgen.generator.custom.features.SurfaceFeatureGenerator.generate(SurfaceFeatureGenerator.java:64) ~[SurfaceFeatureGenerator.class:?]
    at cubicchunks.worldgen.generator.custom.features.VariantFeatureGenerator.generate(VariantFeatureGenerator.java:57) ~[VariantFeatureGenerator.class:?]
    at cubicchunks.worldgen.generator.custom.features.MultiFeatureGenerator.generate(MultiFeatureGenerator.java:45) ~[MultiFeatureGenerator.class:?]
    at cubicchunks.worldgen.generator.custom.CustomPopulationProcessor.populate(CustomPopulationProcessor.java:63) ~[CustomPopulationProcessor.class:?]
    at cubicchunks.world.type.CustomCubicChunksWorldType$1.populate(CustomCubicChunksWorldType.java:73) ~[CustomCubicChunksWorldType$1.class:?]
    at cubicchunks.server.ServerCubeCache.lambda$getCube$0(ServerCubeCache.java:352) ~[ServerCubeCache.class:?]
    at cubicchunks.util.Box.forEachPoint(Box.java:44) ~[Box.class:?]
    at cubicchunks.server.ServerCubeCache.getCube(ServerCubeCache.java:347) ~[ServerCubeCache.class:?]
    at cubicchunks.server.PlayerCubeMapEntry.providePlayerCube(PlayerCubeMapEntry.java:133) ~[PlayerCubeMapEntry.class:?]
    at cubicchunks.server.PlayerCubeMap.tick(PlayerCubeMap.java:263) ~[PlayerCubeMap.class:?]
    at net.minecraft.world.WorldServer.tick(WorldServer.java:230) ~[WorldServer.class:?]
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:772) ~[MinecraftServer.class:?]
    ... 4 more
```

**Comment by Barteks2x** [comment]
Fixed in https://github.com/Barteks2x/CubicChunks/commit/bcab32ec7b53e0605c9508c6682fb2d6545bc4a0
