### ISSUE TITLE
Fail if coremod is not loaded (Was: Recent refactor breaks world loading)

### ISSUE THREAD

**Issue by Boreeas** [Barteks2x/CubicChunks#88]
Loading or generating a new world crashes the server with the following stack trace

```
java.lang.ClassCastException: net.minecraft.world.WorldServerMulti cannot be cast to cubicchunks.world.ICubicWorld
	at cubicchunks.CommonEventHandler.onWorldLoad(CommonEventHandler.java:48) ~[CommonEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_11_CommonEventHandler_onWorldLoad_Load.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) ~[EventBus.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:97) ~[IntegratedServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.startServer(IntegratedServer.java:124) ~[IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:496) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
```

**Comment by Boreeas** [comment]
1fae6ca01a9f8189fe25c623d2827c4b0f4afb76 is the first bad commit

**Comment by Boreeas** [comment]
Probably cause:

```
[13:27:23] [main/ERROR] [FML]: Coremod CoreModLoadingPlugin: Unable to class load the plugin cubicchunks.asm.CoreModLoadingPlugin
java.lang.ClassNotFoundException: cubicchunks.asm.CoreModLoadingPlugin
```

**Comment by Boreeas** [comment]
Looks like I just forgot to update the command line core mod loading. We should probably fail transparently if the core mod is not loaded

**Comment by Barteks2x** [comment]
This is only dev environment issue. Outside of dev environment mixin will load ppoperly without commandline options.
